import { createTheme } from '@mui/material';
import {
  errorContrast,
  errorDark,
  errorLight,
  errorMain,
  infoContrast,
  infoDark,
  infoLight,
  infoMain,
  primaryContrast,
  primaryDark,
  primaryLight,
  primaryMain,
  secondaryContrast,
  secondaryDark,
  secondaryLight,
  secondaryMain,
  successContrast,
  successDark,
  successLight,
  successMain,
  textPrimary,
  warningContrast,
  warningDark,
  warningLight,
  warningMain,
} from '../tokens/colors';
import {
  actionActive,
  actionDisabled,
  actionDisabledBackground,
  actionFocus,
  actionHover,
  actionSelected,
} from '../tokens/actions';
import {
  h1Size,
  h1Weight,
  h1LineHeight,
  h2Size,
  h2Weight,
  h2LineHeight,
  h3Size,
  h3Weight,
  h3LineHeight,
  h4Size,
  h4Weight,
  h4LineHeight,
  h5Size,
  h5Weight,
  h5LineHeight,
  h6Size,
  h6Weight,
  h6LineHeight,
  subtitle1Size,
  subtitle1Weight,
  subtitle1LineHeight,
  subtitle2Size,
  subtitle2Weight,
  subtitle2LineHeight,
  body1Size,
  body1Weight,
  body1LineHeight,
  body2Size,
  body2Weight,
  body2LineHeight,
  captionSize,
  captionWeight,
  captionLineHeight,
  overlineSize,
  overlineWeight,
  overlineLineHeight,
} from '../tokens/typography';

export const theme = createTheme({
  typography: {
    allVariants: {
      color: textPrimary,
    },
    h1: {
      fontSize: h1Size,
      fontWeight: h1Weight,
      lineHeight: h1LineHeight,
    }, 
    h2: {
      fontSize: h2Size,
      fontWeight: h2Weight,
      lineHeight: h2LineHeight,
    },
    h3: {
      fontSize: h3Size,
      fontWeight: h3Weight,
      lineHeight: h3LineHeight,
    },
    h4: {
      fontSize: h4Size,
      fontWeight: h4Weight,
      lineHeight: h4LineHeight,
    },
    h5: {
      fontSize: h5Size,
      fontWeight: h5Weight,
      lineHeight: h5LineHeight,
    },
    h6: {
      fontSize: h6Size,
      fontWeight: h6Weight,
      lineHeight: h6LineHeight,
    },
    subtitle1: {
      fontSize: subtitle1Size,
      fontWeight: subtitle1Weight,
      lineHeight: subtitle1LineHeight,
    },
    subtitle2: {
      fontSize: subtitle2Size,
      fontWeight: subtitle2Weight,
      lineHeight: subtitle2LineHeight,
    },
    body1: {
      fontSize: body1Size,
      fontWeight: body1Weight,
      lineHeight: body1LineHeight,
    },
    body2: {
      fontSize: body2Size,
      fontWeight: body2Weight,
      lineHeight: body2LineHeight,
    },
    caption: {
      fontSize: captionSize,
      fontWeight: captionWeight,
      lineHeight: captionLineHeight,
    },
    overline: {
      fontSize: overlineSize,
      fontWeight: overlineWeight,
      lineHeight: overlineLineHeight,
    },
  },
  palette: {
    primary: {
      main: primaryMain,
      dark: primaryDark,
      light: primaryLight,
      contrastText: primaryContrast,
    },
    secondary: {
      main: secondaryMain,
      dark: secondaryDark,
      light: secondaryLight,
      contrastText: secondaryContrast,
    },
    error: {
      main: errorMain,
      dark: errorDark,
      light: errorLight,
      contrastText: errorContrast,
    },
    warning: {
      main: warningMain,
      dark: warningDark,
      light: warningLight,
      contrastText: warningContrast,
    },
    info: {
      main: infoMain,
      dark: infoDark,
      light: infoLight,
      contrastText: infoContrast,
    },
    success: {
      main: successMain,
      dark: successDark,
      light: successLight,
      contrastText: successContrast,
    },
    action: {
      active: actionActive,
      hover: actionHover,
      selected: actionSelected,
      disabled: actionDisabled,
      disabledBackground: actionDisabledBackground,
      focus: actionFocus,
    },
  },
});
